package wizard

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
)

// Marshal renders the Config as depdog.yaml. Output is deterministic and
// matches the repo's own hand-written style: one merged components block where
// each entry carries its path(s) and, inline, the rule saying who it may import.
// Name and rule columns are aligned; component intent trails as a comment. The
// result is guaranteed to parse — the cli round-trips it through config.Parse
// before writing — but Marshal itself only guards the basics.
func (c Config) Marshal() ([]byte, error) {
	if len(c.Components) == 0 {
		return nil, errors.New("no components to write")
	}
	if c.Policy != PolicyDeny && c.Policy != PolicyAllow {
		return nil, fmt.Errorf("invalid policy %q", c.Policy)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# depdog.yaml — generated by `depdog init` (preset: %s, default: %s).\n", c.Preset, c.Policy)
	b.WriteString("# Each component lists its path glob(s) and, inline, who it may import.\n")
	if c.Policy == PolicyDeny {
		b.WriteString("# default: deny is the whitelist stance — a rule-less component may import nothing.\n")
	} else {
		b.WriteString("# default: allow is the blacklist stance — a rule-less component may import anything.\n")
	}
	b.WriteString("# Review this file, then run `depdog check`.\n")
	b.WriteString("version: 2\n\n")

	nameW := 0
	for _, comp := range c.Components {
		if n := len(comp.Name) + 1; n > nameW { // +1 for the colon
			nameW = n
		}
	}

	// Align the inline rule key across components that carry one: find the
	// widest `{ path: <patterns>,` prefix and pad the rest up to it.
	prefixW := 0
	for _, comp := range c.Components {
		if c.ruleInner(comp) == "" {
			continue
		}
		if n := len("{ path: " + renderPath(comp.Patterns) + ","); n > prefixW {
			prefixW = n
		}
	}

	b.WriteString("components:\n")
	rows := make([]string, len(c.Components))
	commentAt := 0
	for i, comp := range c.Components {
		rows[i] = fmt.Sprintf("  %-*s %s", nameW, comp.Name+":", c.entryBody(comp, prefixW))
		if comp.Comment != "" && len(rows[i]) > commentAt {
			commentAt = len(rows[i])
		}
	}
	for i, comp := range c.Components {
		if comp.Comment == "" {
			b.WriteString(rows[i])
		} else {
			fmt.Fprintf(&b, "%-*s  # %s", commentAt, rows[i], comp.Comment)
		}
		b.WriteByte('\n')
	}

	fmt.Fprintf(&b, "\ndefault: %s\n", c.Policy)

	return []byte(b.String()), nil
}

// entryBody renders a component's `{ path: ..., allow/deny: [...] }` value.
// prefixW aligns the rule key across entries; entries with no rule render just
// `{ path: ... }`.
func (c Config) entryBody(comp Component, prefixW int) string {
	inner := c.ruleInner(comp)
	if inner == "" {
		return "{ path: " + renderPath(comp.Patterns) + " }"
	}
	prefix := "{ path: " + renderPath(comp.Patterns) + ","
	if pad := prefixW - len(prefix); pad > 0 {
		prefix += strings.Repeat(" ", pad)
	}
	return prefix + " " + inner + " }"
}

// RuleInner renders a component's inline rule for the given policy without the
// braces — "allow: [...]" under deny, "deny: [...]" under allow — or "" when the
// component is unconstrained under that stance. `init --merge` uses it to build
// each merged entry's `{ path: ..., <rule> }` value.
func RuleInner(comp Component, policy string) string {
	return Config{Policy: policy}.ruleInner(comp)
}

// ruleInner renders the inline rule body (no braces) for the active policy, or
// "" when the component is unconstrained (nothing to allow under deny, nothing
// to deny under allow).
func (c Config) ruleInner(comp Component) string {
	var (
		refs []string
		key  string
	)
	if c.Policy == PolicyDeny {
		refs, key = comp.Allow, "allow"
	} else {
		refs, key = comp.Deny, "deny"
	}
	if len(refs) == 0 {
		return ""
	}
	return fmt.Sprintf("%s: %s", key, renderList(refs, true))
}

// renderPath renders a component's path field: a quoted scalar for a single
// pattern, a flow list for several.
func renderPath(patterns []string) string {
	if len(patterns) == 1 {
		return strconv.Quote(patterns[0])
	}
	return renderList(patterns, false)
}

// renderList renders a YAML flow sequence. Patterns are always double-quoted;
// refs are bare except "*", which must be quoted to stay a string.
func renderList(items []string, refs bool) string {
	out := make([]string, len(items))
	for i, it := range items {
		switch {
		case !refs:
			out[i] = strconv.Quote(it)
		case it == "*":
			out[i] = `"*"`
		default:
			out[i] = it
		}
	}
	return "[" + strings.Join(out, ", ") + "]"
}
