package wizard

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
)

// Marshal renders the Config as depdog.yaml. Output is deterministic and
// matches the repo's own hand-written style: name columns aligned, rules in
// flow form ({ allow: [...] }), component intent as aligned trailing comments.
// The result is guaranteed to parse — the cli round-trips it through
// config.Parse before writing — but Marshal itself only guards the basics.
func (c Config) Marshal() ([]byte, error) {
	if len(c.Components) == 0 {
		return nil, errors.New("no components to write")
	}
	if c.Policy != PolicyDeny && c.Policy != PolicyAllow {
		return nil, fmt.Errorf("invalid policy %q", c.Policy)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# depdog.yaml — generated by `depdog init` (preset: %s, policy: %s).\n", c.Preset, c.Policy)
	b.WriteString("# Components map package directories to layers; rules declare who may import whom.\n")
	if c.Policy == PolicyDeny {
		b.WriteString("# policy: deny is the whitelist stance — only imports a rule allows are permitted.\n")
	} else {
		b.WriteString("# policy: allow is the blacklist stance — everything passes except what a rule denies.\n")
	}
	b.WriteString("# Review this file, then run `depdog check`.\n")
	b.WriteString("version: 1\n\n")

	nameW := 0
	for _, comp := range c.Components {
		if n := len(comp.Name) + 1; n > nameW { // +1 for the colon
			nameW = n
		}
	}

	// Components block: aligned name column, aligned trailing comments.
	b.WriteString("components:\n")
	rows := make([]string, len(c.Components))
	commentAt := 0
	for i, comp := range c.Components {
		rows[i] = fmt.Sprintf("  %-*s %s", nameW, comp.Name+":", renderList(comp.Patterns, false))
		if comp.Comment != "" && len(rows[i]) > commentAt {
			commentAt = len(rows[i])
		}
	}
	for i, comp := range c.Components {
		if comp.Comment == "" {
			b.WriteString(rows[i])
		} else {
			fmt.Fprintf(&b, "%-*s  # %s", commentAt, rows[i], comp.Comment)
		}
		b.WriteByte('\n')
	}

	fmt.Fprintf(&b, "\npolicy: %s\n", c.Policy)

	// Rules block: only components constrained under the current policy appear.
	var ruleRows []string
	for _, comp := range c.Components {
		body := c.ruleBody(comp)
		if body == "" {
			continue
		}
		ruleRows = append(ruleRows, fmt.Sprintf("  %-*s %s", nameW, comp.Name+":", body))
	}
	if len(ruleRows) > 0 {
		b.WriteString("\nrules:\n")
		for _, r := range ruleRows {
			b.WriteString(r)
			b.WriteByte('\n')
		}
	}

	return []byte(b.String()), nil
}

// RuleBody renders the flow-form rule body for comp under the given policy
// ("{ allow: [...] }" under deny, "{ deny: [...] }" under allow), or "" when
// the component is unconstrained under that stance. `init --merge` uses it to
// add a rule alongside each merged component.
func RuleBody(comp Component, policy string) string {
	return Config{Policy: policy}.ruleBody(comp)
}

// ruleBody renders a component's rule for the active policy, or "" when the
// component is unconstrained (nothing to allow under deny, nothing to deny
// under allow).
func (c Config) ruleBody(comp Component) string {
	var (
		refs []string
		key  string
	)
	if c.Policy == PolicyDeny {
		refs, key = comp.Allow, "allow"
	} else {
		refs, key = comp.Deny, "deny"
	}
	if len(refs) == 0 {
		return ""
	}
	return fmt.Sprintf("{ %s: %s }", key, renderList(refs, true))
}

// renderList renders a YAML flow sequence. Patterns are always double-quoted;
// refs are bare except "*", which must be quoted to stay a string.
func renderList(items []string, refs bool) string {
	out := make([]string, len(items))
	for i, it := range items {
		switch {
		case !refs:
			out[i] = strconv.Quote(it)
		case it == "*":
			out[i] = `"*"`
		default:
			out[i] = it
		}
	}
	return "[" + strings.Join(out, ", ") + "]"
}
